# Generated by Django 4.2.5 on 2023-10-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('state1', 'One'), ('state2', 'Two'), ('state3', 'Bagmati'), ('state4', 'Gandaki'), ('state5', 'Lumbini'), ('state6', 'Karnali'), ('state7', 'Sudurpashchim')], max_length=50),
        ),
    ]
