# Generated by Django 4.2.5 on 2023-10-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
    ]
